name: build32

on:
  workflow_dispatch:
    inputs:
      packages:
        description: 'Packages to build (space-delimited)'
        required: true
      repository:
        description: 'Repository to check out'
        required: true
        default: msys2/MSYS2-packages
      ref:
        description: 'Ref of repository to check out'
        required: true
        default: master
      install_extras:
        description: 'Extra packages to install'
      dont_upload:
        description: 'Don''t upload artifacts to repo'
        required: false
        default: false

env:
  PACMAN_REPOSITORY_NAME: build32
  DEPLOY_PROVIDER: tip
  PACMAN_REPOSITORY_URL: https://github.com/${{ github.repository }}/releases/download/repo

jobs:
  build32:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.ref }}
          path: r

      - uses: jeremyd2019/setup-msys2@v2_32
        with:
          msystem: MSYS
          install: git base-devel msys2-devel
          update: true
          bitness: 32

      - name: Query MSYS2 root dir
        id: msys2
        shell: powershell
        run: Write-Output ('::set-output name=rootdir::{0}' -f (msys2 -c 'cygpath -w /'))

      - name: Update
        continue-on-error: true
        run: ./update.sh

      - name: Kill
        shell: cmd
        run: |
          "%windir%\SysWOW64\WindowsPowerShell\v1.0\PowerShell.exe" -NoProfile -ExecutionPolicy Bypass -Command "Get-Process | Where-Object { $_.Modules.ModuleName -contains 'msys-2.0.dll' } | Stop-Process -Force"

      - name: Install special
        if: ${{ github.event.inputs.install_extras != '' }}
        run: pacman --noconfirm --noprogressbar -S --needed --overwrite '*' ${{ github.event.inputs.install_extras }}

      - name: Kill 2
        if: ${{ github.event.inputs.install_extras != '' }}
        shell: cmd
        run: |
          "%windir%\SysWOW64\WindowsPowerShell\v1.0\PowerShell.exe" -NoProfile -ExecutionPolicy Bypass -Command "Get-Process | Where-Object { $_.Modules.ModuleName -contains 'msys-2.0.dll' } | Stop-Process -Force"

      - name: Auto-Rebase 1
        shell: cmd
        run: |
          call "${{ steps.msys2.outputs.rootdir }}\autorebase.bat"

      - name: Update again
        run: ./update.sh

      - name: Kill 3
        shell: cmd
        run: |
          "%windir%\SysWOW64\WindowsPowerShell\v1.0\PowerShell.exe" -NoProfile -ExecutionPolicy Bypass -Command "Get-Process | Where-Object { $_.Modules.ModuleName -contains 'msys-2.0.dll' } | Stop-Process -Force"

      - name: Auto-Rebase 2 and subst
        shell: cmd
        run: |
          del "${{ steps.msys2.outputs.rootdir }}\etc\rebase.db.*"
          call "${{ steps.msys2.outputs.rootdir }}\autorebase.bat"
          SUBST T: .

      - name: Build32
        run: cd /t/ && ./build32.sh ${{ github.event.inputs.packages }}

      - name: un-subst
        if: ${{ always() }}
        shell: cmd
        continue-on-error: true
        run: |
          SUBST T: /D

      - uses: actions/upload-artifact@v2
        with:
          name: packages
          path: artifacts/
  staging:
    needs: [ build32 ]
    runs-on: ubuntu-latest
    if: ${{ ! github.event.inputs.dont_upload }}
    steps:

    - uses: actions/download-artifact@v2

    - uses: eine/tip@master
      continue-on-error: true
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: 'repo'
        files: packages/*
