name: build32

on:
  workflow_dispatch:
    inputs:
      packages:
        description: 'Packages to build (space-delimited)'
        required: true
      repository:
        description: 'Repository to check out'
        required: true
        default: msys2/MSYS2-packages
      ref:
        description: 'Ref of repository to check out'
        required: true
        default: master
      install_extras:
        description: 'Extra packages to install'
      dont_upload:
        description: 'Don''t upload artifacts to release'
        required: false
        default: false
      release_name:
        description: 'Release/tag to upload to'
        required: true
        default: repo
      repo_db_name:
        description: 'Name of the pacman database'
        required: true
        default: build32

env:
  PACMAN_REPOSITORY_NAME: ${{ github.event.inputs.repo_db_name }}
  DEPLOY_PROVIDER: tip
  PACMAN_REPOSITORY_URL: https://github.com/${{ github.repository }}/releases/download/${{ github.event.inputs.release_name }}

jobs:
  build32:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.ref }}
          path: r

      - uses: jeremyd2019/setup-msys2@v2_build32
        with:
          msystem: MSYS
          install: git base-devel msys2-devel ${{ github.event.inputs.install_extras }}
          update: true
          bitness: 32

      - name: Get msys2 root
        id: msys2
        shell: powershell
        run: Write-Output ('::set-output name=rootdir::{0}' -f (msys2 -c 'cygpath -w /'))

      - name: Build32
        run: ./build32.sh ${{ github.event.inputs.packages }}

      - uses: actions/upload-artifact@v2
        with:
          name: packages
          path: artifacts/
  staging:
    needs: [ build32 ]
    runs-on: ubuntu-latest
    if: ${{ ! github.event.inputs.dont_upload }}
    steps:

    - uses: actions/download-artifact@v2

    - uses: eine/tip@master
      continue-on-error: true
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.event.inputs.release_name }}
        files: packages/*
