name: build32

on:
  workflow_dispatch:
    inputs:
      packages:
        description: 'Packages to build (space-delimited)'
        required: true
      repository:
        description: 'Repository to check out'
        required: true
        default: msys2/MSYS2-packages
      ref:
        description: 'Ref of repository to check out'
        required: true
        default: master

env:
  PACMAN_REPOSITORY_NAME: build32
  DEPLOY_PROVIDER: tip
  PACMAN_REPOSITORY_URL: https://github.com/${{ github.repository }}/releases/download/repo

jobs:
  build32:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.ref }}
          path: r

      - uses: jeremyd2019/setup-msys2@v2_32
        with:
          msystem: MSYS
          install: git base-devel msys2-devel
          update: true
          bitness: 32

      - name: Build32
        run: ./build32.sh ${{ github.event.inputs.packages }}

      - uses: actions/upload-artifact@v2
        with:
          name: packages
          path: artifacts/
  staging:
    needs: [ build32 ]
    runs-on: ubuntu-latest
    steps:

    - uses: actions/download-artifact@v2

    - uses: eine/tip@master
      continue-on-error: true
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: 'repo'
        files: packages/*
